version: "3"
services:
  test_database:
    platform: linux/x86_64
    container_name: db
    image: mysql
    environment:
      MYSQL_DATABASE: restDB
      MYSQL_ROOT_PASSWORD: 12345678!
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  test_redis:
    image: redis
    ports:
      - 6379:6379

  test_application:
    build: .
    ports:
      - 5000:8088
    depends_on:
      - test_database
      - test_redis


